# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmU7_Jf6XeY_mfbEd-52Hyhwa4KbiDtg
"""

import pandas as pd
import joblib


model = joblib.load("student_model.pkl")


new_student = pd.DataFrame({
    "Hours_Studied": [6],
    "Attendance": [90],
    "Assignments": [8],
    "Sleep_Hours": [7],
    "Previous_Score": [75]
})


prediction = model.predict(new_student)
print("Predicted Exam Score:", prediction[0])