# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XA64DuwGwXDXteyqZH7uLqIXHdBNjGC0
"""

import pandas as pd
from sklearn.model_selection import train_test_split


def load_data(path):
    data = pd.read_csv(path)
    return data


def preprocess_data(data):

    X = data.drop("Exam_Score", axis=1)
    y = data["Exam_Score"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    return X_train, X_test, y_train, y_test