# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCbbkHZHfrsCjPvHBfcnVOmsMs10K_8Z
"""

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib

from preprocessing import load_data, preprocess_data


data = load_data("dataset/student_performance_300.csv")

X_train, X_test, y_train, y_test = preprocess_data(data)


lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_predictions = lr_model.predict(X_test)

print("Linear Regression Results")
print("MSE:", mean_squared_error(y_test, lr_predictions))
print("R2:", r2_score(y_test, lr_predictions))

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

print("\nRandom Forest Results")
print("MSE:", mean_squared_error(y_test, rf_predictions))
print("R2:", r2_score(y_test, rf_predictions))

joblib.dump(rf_model, "student_model.pkl")

print("\nModel saved as student_model.pkl")